name: ESP32SwarmManager
options:
  bundleIdPrefix: com.esp32swarm
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.2"
  createIntermediateGroups: true

targets:
  ESP32SwarmManager:
    type: application
    platform: iOS
    sources:
      - path: ESP32SwarmManager
        excludes:
          - "Preview Content/**"
    resources:
      - path: ESP32SwarmManager/Resources/Assets.xcassets
      - path: ESP32SwarmManager/Resources/Info.plist
        buildPhase: none
    settings:
      base:
        INFOPLIST_FILE: ESP32SwarmManager/Resources/Info.plist
        GENERATE_INFOPLIST_FILE: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: com.esp32swarm.manager
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.0"
        INFOPLIST_KEY_CFBundleDisplayName: "ESP32 Swarm"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        DEVELOPMENT_ASSET_PATHS: "\"ESP32SwarmManager/Preview Content\""
        ENABLE_PREVIEWS: YES
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
